import type { FullScrapeResult, ProjectContext } from '../shared/types';

export function generateClaudeMd(
  scrapeResult: FullScrapeResult,
  projectContext: ProjectContext,
  generatedContent?: string
): string {
  const { projectName, targetUrl, designTokens, typography, accessibility, components } = scrapeResult;

  const topColors = designTokens.colors.slice(0, 10).map(c => `  - \`${c.value}\` (used ${c.count}x)`).join('\n');
  const topFonts = typography.fontFamilies.slice(0, 5).map(f => `  - ${f.family} (${f.count} elements)`).join('\n');
  const componentList = components.slice(0, 20).map(c => `  - ${c.name} (${c.type})`).join('\n');

  if (generatedContent) {
    return generatedContent;
  }

  return `# ${projectName} — UX/UI Design Implementation Guide

> Generated by UX Design Scraper using the Double Black Box Method
> Source: ${targetUrl}
> Generated: ${new Date().toISOString()}

---

## Project Context

- **Goal**: ${projectContext.goal}
- **Industry**: ${projectContext.industry}
- **Target Audience**: ${projectContext.targetAudience}
- **Design Style**: ${projectContext.designStyle}
${projectContext.competitors?.length ? `- **Competitors**: ${projectContext.competitors.join(', ')}` : ''}

---

## The Double Black Box Method

This project follows the Double Black Box design process — a 6-phase methodology designed for teams building with AI.

### Phase Model

| Phase | Black Box | Mode | Your Task |
|-------|-----------|------|-----------|
| 01 — Discover | BB1: User Space | Diverge | Review scraped research data in \`/analysis/\` |
| 02 — Define | BB1: User Space | Converge | Define personas from \`/knowledge-base/role-experience.md\` |
| GATE | Transition | LOCKED | Confirm design brief before proceeding |
| 03 — Diverge | BB2: Design Space | Diverge | Generate 3+ design directions from \`/design-tokens/\` |
| 04 — Develop | BB2: Design Space | Build | Build components from \`/scraped-code/\` and \`/prompts/\` |
| 05 — Deliver | BB2: Design Space | Converge | Final specs, handoff, component library |
| 06 — Measure | Post-ship | Iterate | Review heatmaps in \`/assets/heatmaps/\` |

---

## Design Team Personas

### VP / Head of Design
- **Experience**: 10+ years in product design, 3+ years leading cross-functional teams
- **Core Skills**: Systems thinking at scale, executive communication, design system architecture
- **Role in This Project**: Owns the design vision. Enforces gate discipline. Reviews all design decisions against the brief.
- **Benchmarks**: Jony Ive (Apple), Julie Zhuo (Facebook), Tony Fadell (Nest)

### UX Research Lead
- **Experience**: 5-8 years in UX research (qualitative + quantitative)
- **Core Skills**: Interview synthesis, journey mapping, persona construction, statistical literacy
- **Role in This Project**: Owns Phase 01-02. Validates personas against behavioral data. Manages the research repository.
- **Benchmarks**: Erika Hall (Mule Design), Steve Portigal, Nielsen Norman Group

### Senior UX Designer (2-3 FTEs)
- **Experience**: 5-8 years in product UX design with shipped multi-screen systems
- **Core Skills**: Information architecture, interaction design, Figma mastery, all-fidelity design
- **Role in This Project**: Leads Phase 03-04. Owns IA, wireframes, flows, and prototype construction.
- **Benchmarks**: Luke Wroblewski, Dan Saffer, IDEO designers, Stripe/Linear/Vercel senior designers

### UI Designer / Visual Designer
- **Experience**: 4-7 years in visual/UI design with design system ownership
- **Core Skills**: Typography, color theory, grid systems, icon design, motion tool proficiency
- **Role in This Project**: Translates wireframes to high-fidelity visuals. Owns the visual design system tokens.
- **Benchmarks**: Dieter Rams, Jessica Hische, Stripe design team, Refactoring UI

### Interaction Designer / Motion Designer
- **Experience**: 3-6 years in interaction/motion design for digital products
- **Core Skills**: After Effects, Lottie, ProtoPie, animation principles, CSS animation knowledge
- **Role in This Project**: Designs all animation, transition, and micro-interaction behaviors.
- **Benchmarks**: Google Material Motion team, Stripe animation team, Apple HIG

### Design Systems Engineer
- **Experience**: 5+ years spanning design AND frontend engineering
- **Core Skills**: Figma + React/TypeScript, design tokens (Style Dictionary), Storybook, accessibility implementation
- **Role in This Project**: Bridges design and code. Maintains component library as single source of truth.
- **Benchmarks**: Jina Anne (Salesforce Lightning), Nathan Curtis (EightShapes)

---

## Design System Reference

### Color Palette (Top 10)
${topColors}

### Typography
${topFonts}

### Components Identified (${components.length} total)
${componentList}

### Accessibility Score
- Overall: ${accessibility.overallScore}/100
- WCAG Level: ${accessibility.wcagLevel}
- Contrast Issues: ${accessibility.contrastIssues.length}
- Missing Alt Text: ${accessibility.missingAltText.length}
- Missing ARIA Labels: ${accessibility.missingAriaLabels.length}

---

## Workflow Prompt Chain

Follow these steps in order when using Claude Code to build the design:

### Step 1: Foundation Setup
\`\`\`
Read /design-tokens/colors.json, typography.json, spacing.json, shadows.json.
Create a Tailwind config and CSS custom properties matching these exact tokens.
\`\`\`

### Step 2: Component Library
\`\`\`
Read /scraped-code/components/ for reference HTML/CSS.
Read /prompts/component-prompts/ for each component specification.
Build React/Tailwind components matching the scraped designs with all state variants.
\`\`\`

### Step 3: Screen Assembly
\`\`\`
Read /prompts/screen-prompts/ for each screen specification.
Read /assets/screenshots/ for visual reference at all breakpoints.
Assemble screens using the component library. Match layout from /analysis/flow-analysis.md.
\`\`\`

### Step 4: Motion & Interaction
\`\`\`
Read /design-tokens/animations.json for timing curves and durations.
Add micro-interactions, transitions, and scroll behaviors matching the scraped patterns.
\`\`\`

### Step 5: Accessibility Pass
\`\`\`
Read /analysis/accessibility-audit.md.
Fix all flagged issues: contrast ratios, ARIA labels, keyboard navigation, focus indicators.
Target WCAG 2.2 AA compliance.
\`\`\`

### Step 6: Performance Optimization
\`\`\`
Read /analysis/performance-report.md.
Optimize images (WebP/AVIF), implement lazy loading, minimize CSS/JS bundle.
Target LCP < 2.5s, CLS < 0.1, INP < 200ms.
\`\`\`

---

## File Reference

| Directory | Contents |
|-----------|----------|
| \`/prompts/master-prompt.md\` | Complete generation prompt |
| \`/prompts/screen-prompts/\` | Per-screen specifications |
| \`/prompts/component-prompts/\` | Per-component specifications |
| \`/prompts/workflow-chain.md\` | Detailed prompt chain |
| \`/design-tokens/\` | Color, typography, spacing, shadow, animation JSONs |
| \`/scraped-code/\` | Raw HTML/CSS from source website |
| \`/assets/screenshots/\` | Multi-breakpoint screenshots |
| \`/assets/icons/\` | Extracted SVG icons |
| \`/assets/heatmaps/\` | Behavioral analytics visuals |
| \`/analysis/\` | Accessibility, performance, conversion, flow reports |
| \`/knowledge-base/\` | Best practices, patterns, role knowledge |

---

## AI Tools Recommended Per Phase

| Phase | Primary Tool | Supporting Tools |
|-------|-------------|-----------------|
| Discover | Claude + Brave Search | Hotjar, FullStory, Perplexity |
| Define | Claude | Figma/FigJam, Miro, Notion AI |
| Diverge | Claude Code + v0 | Figma AI, Midjourney, Relume AI |
| Develop | Claude Code | Figma, ProtoPie, Storybook, Stark |
| Deliver | Claude Code | Figma Dev Mode, Storybook, Linear |
| Measure | Claude + Analytics | Mixpanel, Amplitude, PostHog, FullStory |
`;
}
