import type { FullScrapeResult, ProjectContext } from '../shared/types';

export function generateReadme(
  scrapeResult: FullScrapeResult,
  projectContext: ProjectContext,
  generatedContent?: string
): string {
  if (generatedContent) return generatedContent;

  return `# ${scrapeResult.projectName}

> UX/UI Design Intelligence Package
> Scraped from: ${scrapeResult.targetUrl}
> Generated: ${new Date().toISOString()}

## What Is This?

This folder contains a complete UX/UI design intelligence package generated by the **UX Design Scraper** Chrome extension. It includes design tokens, component specifications, analysis reports, and prompt chains ready for use in a **Claude Code** session to rebuild this design.

## Quick Start

1. Open this folder in your Claude Code project
2. Read \`CLAUDE.md\` for the full design team personas and workflow
3. Follow the prompt chain in \`prompts/workflow-chain.md\`
4. Reference \`prompts/master-prompt.md\` for the complete generation instructions

## Contents

### /design-tokens/
Design system tokens extracted from the live website:
- \`colors.json\` — ${scrapeResult.designTokens.colors.length} unique colors
- \`typography.json\` — ${scrapeResult.typography.fontFamilies.length} font families
- \`spacing.json\` — ${scrapeResult.designTokens.spacing.length} spacing values
- \`shadows.json\` — ${scrapeResult.designTokens.shadows.length} shadow values
- \`animations.json\` — Animation timing and easing data

### /scraped-code/
Raw HTML and CSS extracted from components on the source website.

### /assets/
- \`screenshots/\` — Full-page screenshots at 375px, 768px, 1280px, 1920px
- \`icons/\` — Extracted SVG icons
- \`heatmaps/\` — Behavioral analytics visualizations (if available)

### /analysis/
- \`accessibility-audit.md\` — WCAG compliance report (Score: ${scrapeResult.accessibility.overallScore}/100)
- \`performance-report.md\` — Core Web Vitals and Lighthouse data
- \`competitor-matrix.md\` — Competitive analysis
- \`flow-analysis.md\` — User flow and friction analysis
- \`conversion-patterns.md\` — CTA, social proof, and form optimization data
- \`copy-tone-guide.md\` — Copy, microcopy, and tone analysis

### /prompts/
- \`master-prompt.md\` — Complete generation prompt for Claude Code
- \`workflow-chain.md\` — Step-by-step implementation workflow
- \`screen-prompts/\` — Per-screen specifications
- \`component-prompts/\` — Per-component specifications

### /knowledge-base/
- \`best-practices.md\` — Industry UX best practices
- \`design-system-docs.md\` — Design system documentation
- \`role-experience.md\` — Team role definitions and expertise
- \`patterns-library.md\` — Reusable design patterns

## Methodology

This package was generated using the **Double Black Box Method** — a 6-phase UX design process:

1. **Discover** — Research and behavioral data collection
2. **Define** — Problem definition, personas, journey maps
3. **Gate** — Design brief approval
4. **Diverge** — Concept exploration and design directions
5. **Develop** — High-fidelity prototypes and design system
6. **Deliver** — Specs, handoff, and component library
7. **Measure** — Analytics, heatmaps, iteration

## Project Context

| Field | Value |
|-------|-------|
| Goal | ${projectContext.goal} |
| Industry | ${projectContext.industry} |
| Target Audience | ${projectContext.targetAudience} |
| Design Style | ${projectContext.designStyle} |
${projectContext.competitors?.length ? `| Competitors | ${projectContext.competitors.join(', ')} |` : ''}
`;
}
