export const MSG = {
  // Chat / Claude AI
  CHAT_SEND: 'CHAT_SEND',
  CHAT_STREAM_CHUNK: 'CHAT_STREAM_CHUNK',
  CHAT_STREAM_DONE: 'CHAT_STREAM_DONE',
  CHAT_ERROR: 'CHAT_ERROR',

  // Brave Search
  BRAVE_SEARCH: 'BRAVE_SEARCH',
  BRAVE_SEARCH_RESULT: 'BRAVE_SEARCH_RESULT',

  // Scrape Pipeline
  START_SCRAPE: 'START_SCRAPE',
  STOP_SCRAPE: 'STOP_SCRAPE',
  SCRAPE_STEP_START: 'SCRAPE_STEP_START',
  SCRAPE_STEP_PROGRESS: 'SCRAPE_STEP_PROGRESS',
  SCRAPE_STEP_COMPLETE: 'SCRAPE_STEP_COMPLETE',
  SCRAPE_STEP_ERROR: 'SCRAPE_STEP_ERROR',
  SCRAPE_ALL_COMPLETE: 'SCRAPE_ALL_COMPLETE',
  SCRAPE_DATA: 'SCRAPE_DATA',

  // Content Script Injection
  INJECT_SCRAPER: 'INJECT_SCRAPER',
  SCRAPER_READY: 'SCRAPER_READY',

  // Execute specific extractor module
  RUN_EXTRACTOR: 'RUN_EXTRACTOR',
  EXTRACTOR_RESULT: 'EXTRACTOR_RESULT',

  // Screenshots
  CAPTURE_SCREENSHOT: 'CAPTURE_SCREENSHOT',
  SCREENSHOT_CAPTURED: 'SCREENSHOT_CAPTURED',

  // Lighthouse / Performance
  RUN_LIGHTHOUSE: 'RUN_LIGHTHOUSE',
  LIGHTHOUSE_RESULT: 'LIGHTHOUSE_RESULT',

  // File Output
  GENERATE_OUTPUT: 'GENERATE_OUTPUT',
  OUTPUT_PROGRESS: 'OUTPUT_PROGRESS',
  OUTPUT_COMPLETE: 'OUTPUT_COMPLETE',

  // Supabase Sync
  SYNC_TO_SUPABASE: 'SYNC_TO_SUPABASE',
  SYNC_PROGRESS: 'SYNC_PROGRESS',
  SYNC_COMPLETE: 'SYNC_COMPLETE',

  // Analytics (Hotjar/FullStory)
  FETCH_HEATMAPS_API: 'FETCH_HEATMAPS_API',
  SCRAPE_HEATMAPS_DOM: 'SCRAPE_HEATMAPS_DOM',
  HEATMAP_DATA: 'HEATMAP_DATA',

  // Scoring
  SCORE_COMPONENTS: 'SCORE_COMPONENTS',
  SCORE_RESULT: 'SCORE_RESULT',

  // Wayback Machine
  FETCH_WAYBACK: 'FETCH_WAYBACK',
  WAYBACK_RESULT: 'WAYBACK_RESULT',

  // Settings/Status
  GET_STATUS: 'GET_STATUS',
  STATUS_UPDATE: 'STATUS_UPDATE',
  GET_SETTINGS: 'GET_SETTINGS',
  SAVE_SETTINGS: 'SAVE_SETTINGS',

  // Multi-Site Scrape
  MULTI_SITE_SCRAPE: 'MULTI_SITE_SCRAPE',
  MULTI_SITE_PROGRESS: 'MULTI_SITE_PROGRESS',
  MULTI_SITE_COMPLETE: 'MULTI_SITE_COMPLETE',

  // Component Reconstruction
  RECONSTRUCT_COMPONENTS: 'RECONSTRUCT_COMPONENTS',
  RECONSTRUCT_PROGRESS: 'RECONSTRUCT_PROGRESS',
  RECONSTRUCT_COMPLETE: 'RECONSTRUCT_COMPLETE',

  // Design Critique
  CRITIQUE_DESIGN: 'CRITIQUE_DESIGN',
  CRITIQUE_RESULT: 'CRITIQUE_RESULT',

  // Persona Generation
  GENERATE_PERSONAS: 'GENERATE_PERSONAS',
  PERSONAS_RESULT: 'PERSONAS_RESULT',

  // Copy Rewriting
  REWRITE_COPY: 'REWRITE_COPY',
  COPY_RESULT: 'COPY_RESULT',

  // A/B Test Recommendations
  GENERATE_AB_TESTS: 'GENERATE_AB_TESTS',
  AB_TESTS_RESULT: 'AB_TESTS_RESULT',

  // Deep Search (Multi-Round Brave)
  DEEP_SEARCH: 'DEEP_SEARCH',
  DEEP_SEARCH_RESULT: 'DEEP_SEARCH_RESULT',

  // Batch Queue
  BATCH_QUEUE_ADD: 'BATCH_QUEUE_ADD',
  BATCH_QUEUE_START: 'BATCH_QUEUE_START',
  BATCH_QUEUE_STATUS: 'BATCH_QUEUE_STATUS',
  BATCH_QUEUE_PROGRESS: 'BATCH_QUEUE_PROGRESS',

  // Knowledge Enrichment
  ENRICH_KNOWLEDGE: 'ENRICH_KNOWLEDGE',
  KNOWLEDGE_RESULT: 'KNOWLEDGE_RESULT',

  // Motion Capture
  CAPTURE_MOTION: 'CAPTURE_MOTION',
  MOTION_RESULT: 'MOTION_RESULT',

  // Workflow Orchestration
  WORKFLOW_START: 'WORKFLOW_START',
  WORKFLOW_PAUSE: 'WORKFLOW_PAUSE',
  WORKFLOW_RESUME: 'WORKFLOW_RESUME',
  WORKFLOW_ABORT: 'WORKFLOW_ABORT',
  WORKFLOW_PHASE_START: 'WORKFLOW_PHASE_START',
  WORKFLOW_PHASE_STEP_START: 'WORKFLOW_PHASE_STEP_START',
  WORKFLOW_PHASE_STEP_PROGRESS: 'WORKFLOW_PHASE_STEP_PROGRESS',
  WORKFLOW_PHASE_STEP_COMPLETE: 'WORKFLOW_PHASE_STEP_COMPLETE',
  WORKFLOW_PHASE_STEP_ERROR: 'WORKFLOW_PHASE_STEP_ERROR',
  WORKFLOW_PHASE_REVIEWING: 'WORKFLOW_PHASE_REVIEWING',
  WORKFLOW_PHASE_APPROVE: 'WORKFLOW_PHASE_APPROVE',
  WORKFLOW_PHASE_REJECT: 'WORKFLOW_PHASE_REJECT',
  WORKFLOW_PHASE_COMPLETE: 'WORKFLOW_PHASE_COMPLETE',
  WORKFLOW_GATE_CHECK: 'WORKFLOW_GATE_CHECK',
  WORKFLOW_GATE_RESULT: 'WORKFLOW_GATE_RESULT',
  WORKFLOW_COMPLETE: 'WORKFLOW_COMPLETE',
  WORKFLOW_STATE_SYNC: 'WORKFLOW_STATE_SYNC',
  WORKFLOW_ROLLBACK: 'WORKFLOW_ROLLBACK',
} as const;

export type MessageType = (typeof MSG)[keyof typeof MSG];
